# Generated by Django 5.0.6 on 2024-06-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('roomno', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usertype', models.IntegerField()),
            ],
        ),
    ]
