# Generated by Django 5.0.6 on 2024-06-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='usertype',
            field=models.CharField(choices=[('Student', 'Student'), ('Supervisor', 'Supervisor'), ('Security', 'Security')], max_length=20),
        ),
    ]
