# Generated by Django 5.0.6 on 2024-06-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_details_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('complaint_type', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Cleanliness', 'Cleanliness'), ('Food', 'Food'), ('Other', 'Other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('student', models.ForeignKey(limit_choices_to={'usertype': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_complaints', to='api.user_details')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'usertype': 'Supervisor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_complaints', to='api.user_details')),
            ],
        ),
    ]
