# Generated by Django 5.0.6 on 2024-07-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_details_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='supervisor',
        ),
    ]
