# Generated by Django 5.0.6 on 2024-06-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_supervisor_alter_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
